# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/alert_ack.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/alert_ack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-sapient_msg/bsi_flex_335_v1_0/alert_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\"\x86\x02\n\x08\x41lertAck\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\x12I\n\x0c\x61lert_status\x18\x02 \x01(\x0e\x32\x33.sapient_msg.bsi_flex_335_v1_0.AlertAck.AlertStatus\x12\x13\n\x06reason\x18\x03 \x01(\tH\x00\x88\x01\x01\"}\n\x0b\x41lertStatus\x12\x1c\n\x18\x41LERT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41LERT_STATUS_ACCEPTED\x10\x01\x12\x19\n\x15\x41LERT_STATUS_REJECTED\x10\x02\x12\x1a\n\x16\x41LERT_STATUS_CANCELLED\x10\x03\x42\t\n\x07_reasonB6\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rAlertAckProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.alert_ack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rAlertAckProtoP\001'
  _globals['_ALERTACK']._serialized_start=81
  _globals['_ALERTACK']._serialized_end=343
  _globals['_ALERTACK_ALERTSTATUS']._serialized_start=207
  _globals['_ALERTACK_ALERTSTATUS']._serialized_end=332
# @@protoc_insertion_point(module_scope)
