# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/associated_detection.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/associated_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8sapient_msg/bsi_flex_335_v1_0/associated_detection.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n\x13\x41ssociatedDetection\x12\x32\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x11\n\tobject_id\x18\x03 \x01(\t\x12Q\n\x10\x61ssociation_type\x18\x04 \x01(\x0e\x32\x32.sapient_msg.bsi_flex_335_v1_0.AssociationRelationH\x01\x88\x01\x01\x42\x0c\n\n_timestampB\x13\n\x11_association_type*\xc4\x01\n\x13\x41ssociationRelation\x12$\n ASSOCIATION_RELATION_UNSPECIFIED\x10\x00\x12$\n ASSOCIATION_RELATION_NO_RELATION\x10\x01\x12\x1f\n\x1b\x41SSOCIATION_RELATION_PARENT\x10\x02\x12\x1e\n\x1a\x41SSOCIATION_RELATION_CHILD\x10\x03\x12 \n\x1c\x41SSOCIATION_RELATION_SIBLING\x10\x04\x42\x41\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\x18\x41ssociatedDetectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.associated_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\030AssociatedDetectionProtoP\001'
  _globals['_ASSOCIATIONRELATION']._serialized_start=355
  _globals['_ASSOCIATIONRELATION']._serialized_end=551
  _globals['_ASSOCIATEDDETECTION']._serialized_start=125
  _globals['_ASSOCIATEDDETECTION']._serialized_end=352
# @@protoc_insertion_point(module_scope)
