# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/location.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/location.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sapient_msg/bsi_flex_335_v1_0/location.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\"J\n\x0cLocationList\x12:\n\tlocations\x18\x01 \x03(\x0b\x32\'.sapient_msg.bsi_flex_335_v1_0.Location\"\xd1\x02\n\x08Location\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0e\n\x01z\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x14\n\x07x_error\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x14\n\x07y_error\x18\x05 \x01(\x01H\x02\x88\x01\x01\x12\x14\n\x07z_error\x18\x06 \x01(\x01H\x03\x88\x01\x01\x12R\n\x11\x63oordinate_system\x18\x07 \x01(\x0e\x32\x37.sapient_msg.bsi_flex_335_v1_0.LocationCoordinateSystem\x12;\n\x05\x64\x61tum\x18\x08 \x01(\x0e\x32,.sapient_msg.bsi_flex_335_v1_0.LocationDatum\x12\x15\n\x08utm_zone\x18\t \x01(\tH\x04\x88\x01\x01\x42\x04\n\x02_zB\n\n\x08_x_errorB\n\n\x08_y_errorB\n\n\x08_z_errorB\x0b\n\t_utm_zone*\xd4\x01\n\x18LocationCoordinateSystem\x12*\n&LOCATION_COORDINATE_SYSTEM_UNSPECIFIED\x10\x00\x12,\n(LOCATION_COORDINATE_SYSTEM_LAT_LNG_DEG_M\x10\x01\x12,\n(LOCATION_COORDINATE_SYSTEM_LAT_LNG_RAD_M\x10\x02\x12$\n LOCATION_COORDINATE_SYSTEM_UTM_M\x10\x05\"\x04\x08\x03\x10\x03\"\x04\x08\x04\x10\x04*g\n\rLocationDatum\x12\x1e\n\x1aLOCATION_DATUM_UNSPECIFIED\x10\x00\x12\x1a\n\x16LOCATION_DATUM_WGS84_E\x10\x01\x12\x1a\n\x16LOCATION_DATUM_WGS84_G\x10\x02\x42\x36\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rLocationProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.location_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rLocationProtoP\001'
  _globals['_LOCATIONCOORDINATESYSTEM']._serialized_start=496
  _globals['_LOCATIONCOORDINATESYSTEM']._serialized_end=708
  _globals['_LOCATIONDATUM']._serialized_start=710
  _globals['_LOCATIONDATUM']._serialized_end=813
  _globals['_LOCATIONLIST']._serialized_start=79
  _globals['_LOCATIONLIST']._serialized_end=153
  _globals['_LOCATION']._serialized_start=156
  _globals['_LOCATION']._serialized_end=493
# @@protoc_insertion_point(module_scope)
