# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/sapient_message.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/sapient_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sapient_msg.bsi_flex_335_v1_0 import alert_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_alert__pb2
from sapient_msg.bsi_flex_335_v1_0 import alert_ack_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_alert__ack__pb2
from sapient_msg.bsi_flex_335_v1_0 import detection_report_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_detection__report__pb2
from sapient_msg.bsi_flex_335_v1_0 import error_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_error__pb2
from sapient_msg import proto_options_pb2 as sapient__msg_dot_proto__options__pb2
from sapient_msg.bsi_flex_335_v1_0 import registration_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_registration__pb2
from sapient_msg.bsi_flex_335_v1_0 import registration_ack_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_registration__ack__pb2
from sapient_msg.bsi_flex_335_v1_0 import status_report_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_status__report__pb2
from sapient_msg.bsi_flex_335_v1_0 import task_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_task__pb2
from sapient_msg.bsi_flex_335_v1_0 import task_ack_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_task__ack__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3sapient_msg/bsi_flex_335_v1_0/sapient_message.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)sapient_msg/bsi_flex_335_v1_0/alert.proto\x1a-sapient_msg/bsi_flex_335_v1_0/alert_ack.proto\x1a\x34sapient_msg/bsi_flex_335_v1_0/detection_report.proto\x1a)sapient_msg/bsi_flex_335_v1_0/error.proto\x1a\x1fsapient_msg/proto_options.proto\x1a\x30sapient_msg/bsi_flex_335_v1_0/registration.proto\x1a\x34sapient_msg/bsi_flex_335_v1_0/registration_ack.proto\x1a\x31sapient_msg/bsi_flex_335_v1_0/status_report.proto\x1a(sapient_msg/bsi_flex_335_v1_0/task.proto\x1a,sapient_msg/bsi_flex_335_v1_0/task_ack.proto\"\xcb\x05\n\x0eSapientMessage\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x1b\n\x0e\x64\x65stination_id\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x43\n\x0cregistration\x18\x04 \x01(\x0b\x32+.sapient_msg.bsi_flex_335_v1_0.RegistrationH\x00\x12J\n\x10registration_ack\x18\x05 \x01(\x0b\x32..sapient_msg.bsi_flex_335_v1_0.RegistrationAckH\x00\x12\x44\n\rstatus_report\x18\x06 \x01(\x0b\x32+.sapient_msg.bsi_flex_335_v1_0.StatusReportH\x00\x12J\n\x10\x64\x65tection_report\x18\x07 \x01(\x0b\x32..sapient_msg.bsi_flex_335_v1_0.DetectionReportH\x00\x12\x33\n\x04task\x18\x08 \x01(\x0b\x32#.sapient_msg.bsi_flex_335_v1_0.TaskH\x00\x12:\n\x08task_ack\x18\t \x01(\x0b\x32&.sapient_msg.bsi_flex_335_v1_0.TaskAckH\x00\x12\x35\n\x05\x61lert\x18\n \x01(\x0b\x32$.sapient_msg.bsi_flex_335_v1_0.AlertH\x00\x12<\n\talert_ack\x18\x0b \x01(\x0b\x32\'.sapient_msg.bsi_flex_335_v1_0.AlertAckH\x00\x12\x35\n\x05\x65rror\x18\x0c \x01(\x0b\x32$.sapient_msg.bsi_flex_335_v1_0.ErrorH\x00\x42\t\n\x07\x63ontentB\x11\n\x0f_destination_idBS\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\x13SapientMessageProtoP\x01\x8a\xea\x30\x13\n\x11\x42SI_Flex_335_v1.0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.sapient_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\023SapientMessageProtoP\001\212\3520\023\n\021BSI_Flex_335_v1.0'
  _globals['_SAPIENTMESSAGE']._serialized_start=583
  _globals['_SAPIENTMESSAGE']._serialized_end=1298
# @@protoc_insertion_point(module_scope)
