# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/task_ack.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/task_ack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sapient_msg.bsi_flex_335_v1_0 import associated_file_pb2 as sapient__msg_dot_bsi__flex__335__v1__0_dot_associated__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sapient_msg/bsi_flex_335_v1_0/task_ack.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\x1a\x33sapient_msg/bsi_flex_335_v1_0/associated_file.proto\"\xf6\x02\n\x07TaskAck\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x46\n\x0btask_status\x18\x02 \x01(\x0e\x32\x31.sapient_msg.bsi_flex_335_v1_0.TaskAck.TaskStatus\x12\x13\n\x06reason\x18\x03 \x01(\tH\x00\x88\x01\x01\x12K\n\x0f\x61ssociated_file\x18\x04 \x01(\x0b\x32-.sapient_msg.bsi_flex_335_v1_0.AssociatedFileH\x01\x88\x01\x01\"\x90\x01\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14TASK_STATUS_ACCEPTED\x10\x01\x12\x18\n\x14TASK_STATUS_REJECTED\x10\x02\x12\x19\n\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n\x12TASK_STATUS_FAILED\x10\x04\x42\t\n\x07_reasonB\x12\n\x10_associated_fileB5\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\x0cTaskAckProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.task_ack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\014TaskAckProtoP\001'
  _globals['_TASKACK']._serialized_start=133
  _globals['_TASKACK']._serialized_end=507
  _globals['_TASKACK_TASKSTATUS']._serialized_start=332
  _globals['_TASKACK_TASKSTATUS']._serialized_end=476
# @@protoc_insertion_point(module_scope)
