# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sapient_msg/bsi_flex_335_v1_0/velocity.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'sapient_msg/bsi_flex_335_v1_0/velocity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,sapient_msg/bsi_flex_335_v1_0/velocity.proto\x12\x1dsapient_msg.bsi_flex_335_v1_0\"\xea\x01\n\x0b\x45NUVelocity\x12\x11\n\teast_rate\x18\x01 \x01(\x01\x12\x12\n\nnorth_rate\x18\x02 \x01(\x01\x12\x14\n\x07up_rate\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x1c\n\x0f\x65\x61st_rate_error\x18\x04 \x01(\x01H\x01\x88\x01\x01\x12\x1d\n\x10north_rate_error\x18\x05 \x01(\x01H\x02\x88\x01\x01\x12\x1a\n\rup_rate_error\x18\x06 \x01(\x01H\x03\x88\x01\x01\x42\n\n\x08_up_rateB\x12\n\x10_east_rate_errorB\x13\n\x11_north_rate_errorB\x10\n\x0e_up_rate_error\"\xb5\x01\n\x10\x45NUVelocityUnits\x12H\n\x15\x65\x61st_north_rate_units\x18\x01 \x01(\x0e\x32).sapient_msg.bsi_flex_335_v1_0.SpeedUnits\x12\x45\n\rup_rate_units\x18\x02 \x01(\x0e\x32).sapient_msg.bsi_flex_335_v1_0.SpeedUnitsH\x00\x88\x01\x01\x42\x10\n\x0e_up_rate_units*^\n\nSpeedUnits\x12\x1b\n\x17SPEED_UNITS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSPEED_UNITS_MS\x10\x01\x12\x13\n\x0fSPEED_UNITS_KPH\x10\x02\"\x04\x08\x03\x10\x03\"\x04\x08\x04\x10\x04\x42\x36\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rVelocityProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sapient_msg.bsi_flex_335_v1_0.velocity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#uk.gov.dstl.sapientmsg.bsiflex335v1B\rVelocityProtoP\001'
  _globals['_SPEEDUNITS']._serialized_start=500
  _globals['_SPEEDUNITS']._serialized_end=594
  _globals['_ENUVELOCITY']._serialized_start=80
  _globals['_ENUVELOCITY']._serialized_end=314
  _globals['_ENUVELOCITYUNITS']._serialized_start=317
  _globals['_ENUVELOCITYUNITS']._serialized_end=498
# @@protoc_insertion_point(module_scope)
